AllCops:
  Exclude:
    - 'ci/*'
    - 'bin/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line
Style/GuardClause:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
