Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line
Style/GuardClause:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
