language: ruby
before_install:
  - git config --global user.email "hello@world.com"
  - git config --global user.name "John Doe"
rvm:
  - 2.5.0
  - ruby-head
os:
  - osx
  - linux
before_install:
  - yes | gem update --system --force
  - gem uninstall bundler
  - gem install bundler -v 2.1.4
  - bundle config git.allow_insecure true
install:
  - bundle install
  - bundle exec rake setup
script:
  - bundle exec rake spec
  - bundle exec rake install
