language: ruby
rvm:
  - 2.5.0
  - 2.6.2
  - 2.7.1
os:
  - osx
  - linux
gemfile:
  - Gemfile
  - ci/Gemfile.rubocop-0.80
  - ci/Gemfile.rubocop-0.81
  - ci/Gemfile.rubocop-0.82
  - ci/Gemfile.rubocop-0.83
  - ci/Gemfile.rubocop-0.84
  - ci/Gemfile.rubocop-0.85
  - ci/Gemfile.rubocop-0.85.1
before_install:
  - yes | gem update --system --force
  - gem uninstall bundler
  - gem install bundler -v 2.1.4
  - bundle config git.allow_insecure true
install:
  - bundle install
  - bundle exec rake setup
  - bundle exec rake git:config
script:
  - bundle exec rake spec
  - bundle exec rake install
  - rfix info
