language: ruby
# cache:
#   bundler: true
#   directories:
#     - $HOME/.rvm
#     - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
rvm:
  - 2.5.0
  - 2.6.2
  - 2.7.1
os:
  - osx
  - linux
gemfile:
  - ci/Gemfile.rubocop-0.80
  - ci/Gemfile.rubocop-0.81
  - ci/Gemfile.rubocop-0.82
  - ci/Gemfile.rubocop-0.83
  - ci/Gemfile.rubocop-0.84
  - ci/Gemfile.rubocop-0.85
  - ci/Gemfile.rubocop-0.85.1
before_install:
  - yes | gem update --system --force
  - gem install bundler
  - bundle config git.allow_insecure true
  - bundle config --local local.cli-ui vendor/shopify/cli-ui
  - make dir fetch
script:
  - bundle exec rake spec
  - bundle exec rake install
  - rfix info
jobs:
  include:
    deploy:
      provider: rubygems
      api_key:
        secure: SJ5rZtQxDnY7aeWIb+gZ1OEV2rDHz8jvMBStHtzPDVtpQeUoo6DJB4FN4Vt5i7VaVk1otkAdOgyANzOQDSB0/1mMBUcy902zKrrUISALeIXp2FpsvjijRdKD0hLJaeX00n/MEJpw671NbzCNboEdiMnCrxSgd775qeQibcv72iRGIY07xv/BLUCtLTmqtjQFQAvcYEFpMQsRE6XEnkRSEOigSsYvNKZrygG4AgUaNY4rcOPqP+Yl26BFHw833GBQeuGgD5a310k3xYwpPc+9I+pTVHcpc4qh2m9kPcNuyDE3OjAMqE3XVn9WXeciZnQR6AQ94n6+5CJyTD3NEv5n58i4kyCLB71YfmPJjO+04+EiCUSZjeECkwACNguzOisdV8Z/vDzfNhI5tvNL7lv3jU05F/lw8LXKR30GBte5BquPY4DjjjXKgKoKl0tbo1bBT0u8LItEaFYoGqRmUiXiHFQNaH02pjBFkjUsyyEgnscWTDtoPxEjyP4aLnW+ESxnJxpwMHHiHPmplrPmK+3hYrTYz9saZyIajLIfcxcGcSSWEHXt2gV5i80pHJFQCc1qV/9d3g8s8sy3N9eKzV6SMYspFTtdKe2Pf7m/nwFt235/ibx0Z4Gyb1TZKze7phv9yAzvAaIb28I3Ye6S2S/ALemlKiu1A/XWtNtOxo8xMNE=
      gem: rfix
      on:
        repo: oleander/rfix-rb
        tags: false
      cleanup: 'false'
