language: ruby
before_install:
  - git config --global user.email "hello@world.com"
  - git config --global user.name "John Doe"
rvm:
  - 2.5.0
  - ruby-head
os:
  - osx
  - linux
script:
  - gem update --system
  - gem install bundler
  - bundler update --bundler
  - bundle install
  - bundle exec rake setup
  - bundle exec rake spec
  - bundle exec rake install
