#!/usr/bin/env ruby

# frozen_string_literal: true

require "rfix"
require "rubocop"
require "rfix/formatter"
require "cli/ui"

should_list_files = false
limit_files       = false
options           = RuboCop::Options.new

display_help      = ARGV.include?("--help")
is_dry            = ARGV.include?("--dry")
config_path       = false
clear_cache       = false

extend Rfix::Log
CLI::UI::StdoutRouter.enable

if root_index = ARGV.index("--root")
  Rfix.set_root(ARGV[root_index + 1])
end

if ARGV.include?("--debug")
  Rfix.debug!
end

options.on("--untracked", "Include untracked files") do
  Rfix.load_untracked!
end

options.on("--main-branch BRANCH", "Set main branch") do |branch|
  Rfix.set_main_branch(branch)
end

options.on("--dry", "No auto correct") do
  say "Will run rfix in {{red:read-only}} mode"
  Rfix.no_auto_correct!
end

options.on("--list-files", "List files found by git") do
  should_list_files = true
end

options.on("--clear-cache", "Clear RuboCop cache") do
  clear_cache = true
end

options.on("--limit-files NUM", Integer, "Limit number of files") do |limit|
  limit_files = limit
end

options.on("--config PATH", "A configuration file") do |path|
  config_path = path
end

options.on("--root PATH", "Project root") do |path|
  # Rfix.set_root(path)
end



Rfix.init!

when "set "Okay, set main branch to {{info:#{branch}}}"
when "branch"
  Rfix.auto_correct!
  abort_message = "No branch passed as second argument"
  unless reference = ARGV.shift
    say_abort abort_message
  end

  # Catches:
  # NOT OK: branch --help
  # OK branch master --help
  say_abort abort_message if reference.start_with?("--")

  # Check if branch exists
  say_abort "Branch {{yellow:#{reference}}} does not exist" unless Rfix.has_branch?(reference)
else
  unless display_help
    say_error "Valid rfix commands are:"
    say_error_sub Rfix.help
    exit 1
  end

  ARGV.unshift(cmd)
end

if path = config_path
  Rfix.load_config do |config|
    config.options_config = path
  end
else
  Rfix.load_config do |config|
    config.for(Dir.pwd)
  end
end

if clear_cache
  say "Clearing cache"
  Rfix.clear_cache!
end

if ref = reference
  say "Compare against {{yellow:#{ref}}}"

  Rfix.load_tracked!(ref)

  paths = Rfix.paths if paths.nil? || paths.empty?

  say_exit "No files to run against" if paths.empty?
end

if limit = limit_files
  say "Limit number of files to {{yellow:#{limit}}}"
  paths = paths.take(limit)
end

if should_list_files
  say "Loaded {{yellow:#{paths.count}}} paths"
  paths.each do |path|
    say "\t" + Rfix.to_relative(path: path)
  end
end

begin
  options, paths = options.parse(ARGV)
rescue OptionParser::MissingArgument => e
  say_abort "[Parser] #{e}"
end



# log_items(paths, title: "Paths to load")

env = RuboCop::CLI::Environment.new(
  Rfix.config.merge(options),
  Rfix.store,
  paths
)

begin
  exit RuboCop::CLI::Command::ExecuteRunner.new(env).run
rescue RuboCop::Error => e
  say_abort e.message
end
