---
name: pre-release
on: [push]
env:
  RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
  GITHUB_API_TOKEN: ${{secrets.API_KEY}}
jobs:
  setup:
    container: ruby:2.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: apt-get update -y
      - run: apt-get install -y bash git libffi-dev build-essential wget cmake

      - run: gem install bundler
      - run: bundle config build.rugged --use-system-libraries
      - run: bundle config build.ffi --use-system-libraries
      - run: gem install rake rspec colorize
      - run: rake libgit2:install

      - run: bundle install --path vendor/bundle
      - run: rake execute:local execute:origin execute:lint execute:branch

      - run: git config user.email "linus@oleander.io"
      - run: git config user.name "Linus Oleander"

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.RUBYGEMS_API_KEY}}"
