---
name: pre-release
on: [push]
env:
  RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
  GITHUB_API_TOKEN: ${{secrets.API_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle exec rake bundle:simple:build
      - run: bundle exec rake bundle:complex:build

      - run: bundle exec rspec --force-color
