---
name: pre-release
on: [push]
env:
  RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
  GITHUB_API_TOKEN: ${{secrets.API_KEY}}
jobs:
  build:
    concurrency:
      group: rfix-test-group
      cancel-in-progress: true
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        gemfile:
          - 0.82
          - 0.83
          - 0.84
          - 0.92
          - 0.93
          - '1.0.0'
          - '1.5.0'
          - '1.5.1'
          - '1.5.2'
          - '1.6.1'
          - '1.7.0'
          - '1.8.0'
          - '1.10.0'
          - '1.11.0'
          - '1.12.0'
          - '1.13.0'
        ruby: [2.6, 2.7, '3.0']

    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.rubocop-${{ matrix.gemfile }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: gem env
      - run: bundle exec rake bundle:simple:build
      - run: bundle exec rake bundle:complex:build
      - run: bundle exec rspec --force-color
