---
name: pre-release
on: [push]
env:
  RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
  GITHUB_API_TOKEN: ${{secrets.API_KEY}}
jobs:
  build:
    container: ruby:2.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: apt-get update -y
      - run: apt-get install -y bash git libffi-dev build-essential wget cmake pkg-config
      - run: gem install bundler rake rspec colorize git rainbow

      - run: git submodule update --init --recursive

      - run: bundle config build.ffi --use-system-libraries
      - run: bundle config path vendor/bundle

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec rake bundle:simple:build
      - run: bundle exec rake bundle:complex:build

      - run: bundle exec rspec
