---
name: pre-release
on: [push]
env:
  RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
  GITHUB_API_TOKEN: ${{secrets.API_KEY}}
jobs:
  build:
    concurrency:
      group: rfix-test-group
      cancel-in-progress: true
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        gemfile:
          - '1.13.0'
        ruby: [2.6]
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.rubocop-${{ matrix.gemfile }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: gem env
      - run: bundle exec rake bundle:simple:build
      - run: bundle exec rake bundle:complex:build

      - run: bundle exec rspec --force-color

      - run: bundle exec rake build
      - run: mkdir -p tmp/bin
      - run: gem install pkg/*.gem --bindir tmp/bin
      - name: Runner
        run: cd tmp/complex && ../../exe/rfix lint 28e229
        env:
          BUNDLE_GEMFILE: ""
